# Stage 1: Build the React app
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

RUN npm install

# Copy the rest of the application code
COPY . .


# Set environment variables

ENV PORT=${PORT}

# RUN npm start

CMD ["npm","start"]
